# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_gradio_tests',
                'doc_host': 'https://f-brockman.github.io',
                'git_url': 'https://github.com/f-brockman/nbdev_gradio_tests',
                'lib_path': 'nbdev_gradio_tests'},
  'syms': {'nbdev_gradio_tests.core': {'nbdev_gradio_tests.core.foo': ('core.html#foo', 'nbdev_gradio_tests/core.py')}}}
